### ISSUE TITLE
1.0.5.0 does not list installed software

### ISSUE THREAD

**Issue by mancitymike** [rzander/sccmclictr#100]
Good Afternoon all.

I have just upgraded to Client Center version 1.0.5.0.

I connect to PC (123456) and it does not display a list of installed software for a pc I connect to.

If I reinstall version 1.0.4.2 and connect to PC (123456) I get a list of Installed Software

is there an issue with 1.0.5.0 ??

Mike

**Comment by rzander** [comment]
What is the PowerShell Version on your target device (`$PSVersionTable.PSVersion` ) ? ClientCenter V1.0.5 is using the Get-CimInstance command...

**Comment by Jrell** [comment]
Have a client with version 2, same problem The client with version 5, works just fine. What is the lowest version that is supported?

**Comment by rzander** [comment]
As defined in the [requirements](https://github.com/rzander/sccmclictr#requirements):
* Windows Management Framework 4.0 (PowerShell 4) on the Host and on the target Computer.

**Comment by kmjohnston** [comment]
It's interesting though, because `Get-CimInstance -query "SELECT * FROM SMS_InstalledSoftware" -namespace "root\CIMV2\sms"` works just fine against a PowerShell 2 remote computer when I run it from a PowerShell console (with the addition of the -ComputerName parameter to specify the remote computer)
