### ISSUE TITLE
StartCom SSL certificate chain is broken

### ISSUE THREAD

**Issue by MickFly** [rzander/sccmclictr#52]
Could you remove or replace the current StartCom SSL signing certificate? Because of vendors blocking StartCom, the install fails on systems not allowing certificates from StartCom.

**Comment by rzander** [comment]
The current certificate is valid from 1.7.2017 until 1.7.2019 and Microsoft does currently only block StarCom certificates issued after after Sept17: https://cloudblogs.microsoft.com/microsoftsecure/2017/08/08/microsoft-to-remove-wosign-and-startcom-certificates-in-windows-10/?source=mmpc

Once the cert nears EOL, i will swicth to another vendor... but for now I do not see a reason to invest in another cert.

**Comment by MickFly** [comment]
I think other security measures on the site I currently work are the cause of this. On my own computer I can run the executable.
But today Sophos Antivirus detected a Trojan in this file.

**Comment by patrikfrisk** [comment]
I have problem installing the tool on a Server 2016 , getting the following error
_"A file that is required cannot be installed because the cabinet file C:\Users\[username]\AppData\Roaming\Zander Tools\Client Center for Configuration Manager1.0.3.9\install\Client Center for Configuration Manager_v1.0.3.91.cab has an invalid digital signature. This may indicate that the cabinet file is corrupt."_
Can this be the same problem that "MickFly" has with StartCom SSL signing certicate

**Comment by rzander** [comment]
I did an install on SRV2016 a few days ago, so I don't think it's a general Problem
Check out: "[Issue 17](https://github.com/rzander/sccmclictr/issues/17)" maybe you aleady have removed StarCom from your trusted CA's ?!

**Comment by rzander** [comment]
vNext will use a Comodo Certificate... Thx for all the donations to get another code signing cert !
