### ISSUE TITLE
Tools App-v 4.6 info

### ISSUE THREAD

**Issue by toto313** [rzander/sccmclictr#60]
Hello,

First, thanks for this very useful tool :-)

I just want to ask a question, it's maybe not an issue.

Since I upgraded to 1.0.4.2, the tools "App-v 4.6 Info" is not available.

I can't find any comment about this deletion, is this normal ?

Regards,
Thomas

![image](https://user-images.githubusercontent.com/37901254/38087127-402fc1f0-3357-11e8-9513-d6aa5e92d262.png)

![image](https://user-images.githubusercontent.com/37901254/38087130-44bef07e-3357-11e8-965e-296de02d82f9.png)

**Comment by rzander** [comment]
Mainstream Support for App-V 4.6 SP3 ended on July 2015...  If you still need the Plugin, copy the file Plugin_AppV46.dll from Version 1.0.3.9...

**Comment by SCCMAdmin** [comment]
Oh wow! I will need this solution for sure. Just because mainstream support ended, doesn't mean there aren't any 4.6 virtual apps out there. 4.6 is on our Win7 part of the fleet (yes a dying breed).

A better question is, how do we manage App-V 5.x apps via Client Center or is there some better tool I've not heard of yet? I'm guessing the answer is they are SCCM Applications and should be easily managed under the Applications area. However you cannot easily manage any application targeting a user. Only applications targeting computers are easily managed/supported in CCCM. Could be a good new thread topic.

**Comment by toto313** [comment]
Thanks for your answer M. Zander. It works.

But I agree with SCCMAdmin, it's not because support ended that it's not used anymore.

His second question is also good. Can we manage APPV 5 packages with Client Center in next release ?

I know we can easily manage them with powershell console, but it can be good to have an interface just to make basic task like show/repair/uninstall packages.

Regards

**Comment by rzander** [comment]
The AppV-4.6 Plugin was written by Mattias Benninge. You have to find someone that creates one for App-V 5... I will not invest time on that...

If you deploy SW to users, make them "available" instead of "required", so the user can decide when and what to install. In case of a problem, users can uninstall and re-install the SW by themselves. No need to contact support...

**Comment by toto313** [comment]
> If you deploy SW to users, make them "available" instead of "required", so the user can decide when and what to install. In case of a problem, users can uninstall and re-install the SW by themselves. No need to contact support...

In some companies, you can't let users to decide which application they can install or not and communicate with them is limited.

Thanks for your answer but, when I read some "...", I understand that like "I don't care". I hope it's not what you mean ;-)

**Comment by rzander** [comment]
Well, I don't care about AppV4.6 that's true ... None of my customers are using AppV5, or if they are using it, it's wrapped in a ConfigMgr application. So I have no business case to invest any time in AppV5 and I don't see AppV as a growing technology. But ask me again in 6 months and it may be different.

I understand the discussion with user based deployments as I hear it "every day" :-) .. but the IT world is changing, processes that are used the last 20 years may become obsolete. The interresting thing is that I mostly get positive feedback from end users if they get more responsibility... IT seems to be more cautious... 

Client Center is not able to manage user based deployments properly because the ConfigMgr Agent does not provide the required API's. In this case "I care" but I can't fix it  :-(

**Comment by SCCMAdmin** [comment]
Thanks for the responses @rzander . 

@toto313 thanks for your posts too. We use App-V5 deployment types and when pointed to devices / computers you can use CCCM to manage them. We generally don't leave applications available, customers will never action them. Required works as you can trust it will happen. ICT has standards to enforce, not forever to wait for a customer who doesn't care.

@rzander using SCCM Client Center 2.0.4.0 (the 2007 tool), it can happily support user advertisements of packages (legacy). I understand that's all via WMI. So via WinRM you are saying you cannot access any part of SCCM to be able to read user deployments pointing to the user for packages or for applications?

**Comment by rzander** [comment]
The "new" Client Center is also using WMI (over WinRM). The Problem is that Packages are completely different than Applications. The API for Applications (WMI) will only show applications for the account that makes the request. So you will only get what your admin account is allowed to see on the target client. 
The user is responsible for his emails, store apps, start menu, file type associations, "Software Center", etc. and not a remote admin....

**Comment by rzander** [comment]
Plugin for AppV46 is now a separate download: https://github.com/rzander/sccmclictr/releases/tag/1.0.4.2

**Comment by SCCMAdmin** [comment]
Very interesting @rzander thanks for explaining. So essentially without the actual user credentials we are trying to support, there is no other easy way to support user targeted applications (something I think we should all be making more use of).
