### ISSUE TITLE
Windows PowerShell Event Logs.  Password Displayed in Plain Text

### ISSUE THREAD

**Issue by Wkizzle** [rzander/sccmclictr#64]
I've confirmed this issue exists all the way back to 1.3.

When using the latest Client Center, if you populate the username and password fields, connect to a machine, and then open a Remote PowerShell Console with the tool, the tool registers the following command in the Event Viewer (Application and Services / Windows PowerShell):
HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoExit -Command $creds = New-Object System.Management.Automation.PSCredential ('domain\user', (ConvertTo-SecureString 'ATemporaryPassw0rd!#' -AsPlainText -force)); Enter-PSSession COMPUTERNAME.DOMAIN.COM -port 5985 -SessionOption (New-SessionOption -NoMachineProfile)

Multiple things wrong with this :)

**Comment by hmmwhatsthisdo** [comment]
It should probably be noted that the real issue here is not that the password is being written to event logs, but rather that it's in the commandline in plain-text in the first place. This is subsequently visible to other users on the machine - regardless of whether or not PoSH event logs are enabled. I'd consider that a higher-risk situation than the event logs themselves.

Insofar as a fix, you could convert the password to a SecureString (then to its byte-string representation) within the Client Center, then pass that through to PowerShell (using `ConvertTo-SecureString`). SecureStrings are serialized using DPAPI user keys, so there should be a much smaller opportunity for other principals (local or remote) to decrypt the string.

As that might be pushing the envelope on command-line length with long passwords (it looks like 8191 is the maximum pre-Win7, 32768 afterwards), you could also generate the PSCredential within Client Center and serialize to disk as CLIXML.
